# Generated by Django 4.1.1 on 2022-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='CI')),
                ('age', models.PositiveIntegerField(default=18)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'ordering': ['id'],
            },
        ),
    ]
