# Generated by Django 4.1.1 on 2022-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='limitacion',
            field=models.BooleanField(default=1, verbose_name='Limitación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='limitacion',
            field=models.BooleanField(default=1, verbose_name='Limitación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='limitaciones',
            field=models.CharField(max_length=500, verbose_name='Limitaciones'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='limitaciones',
            field=models.CharField(max_length=500, verbose_name='Limitaciones'),
        ),
    ]
