# Generated by Django 4.1.1 on 2022-10-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='anno',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
