# Generated by Django 4.1.1 on 2022-10-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_corte_estudiante_alter_estudiante_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia_estudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estudiante'),
        ),
        migrations.AlterField(
            model_name='ausencia_trabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.trabajador'),
        ),
        migrations.AlterField(
            model_name='guardia_estudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estudiante'),
        ),
        migrations.AlterField(
            model_name='guardia_trabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.trabajador'),
        ),
    ]
